"""
Project Euler number 29
Find the number of distinct terms generated by
the sequence of a^b for a and b within the range
of 2 to 100
"""
from time import time

def distinctPower(upperbound):
    rawList = [(x ** y) for x in range(2, upperbound + 1) for y in range(2, upperbound + 1)]
    return len(set(rawList))
    
if __name__ == "__main__":
    limit = int(input("Insert upper bound: "))
    start = time()
    print(distinctPower(limit))
    end = time()
    print("Found in %f seconds" % (end-start))