"""
Project Euler number 56
considering all real numbers generated by
a ^ b where a and b are below 100, what is
the maximum sum of all digits in a single
real number generated?
"""
max = 0
List = [(x ** y) for x in range(100) for y in range(100)]
for i in List:
    if sum(list(map(int, list(str(i))))) > max:
        max = sum(list(map(int, list(str(i)))))
print(max)